<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'sku'         => '8410000001234',
                'title'       => 'Detector EMF K2 Pro',
                'provider'    => 'GhostTech Industries',
                'price'       => 49.99,
                'tax'         => 21,
                'stock'       => 25,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=emf',
                'description' => 'Detector de campos electromagnéticos profesional con 5 niveles de sensibilidad LED. Imprescindible en toda investigación paranormal.',
            ],
            [
                'sku'         => '8410000002345',
                'title'       => 'Grabadora EVP Digital 32GB',
                'provider'    => 'SpiritSound Labs',
                'price'       => 89.95,
                'tax'         => 21,
                'stock'       => 15,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=evp',
                'description' => 'Grabadora de voz de alta sensibilidad. Captura voces electrónicas de fenómenos paranormales con 32GB internos.',
            ],
            [
                'sku'         => '8410000003456',
                'title'       => 'Cámara Térmica Nocturna',
                'provider'    => 'NightVision Corp',
                'price'       => 349.00,
                'tax'         => 21,
                'stock'       => 8,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=camara',
                'description' => 'Cámara de visión nocturna con sensor térmico de alta resolución. Detecta variaciones de temperatura de hasta 0.05°C.',
            ],
            [
                'sku'         => '8410000004567',
                'title'       => 'SpiritBox PSB-7',
                'provider'    => 'GhostTech Industries',
                'price'       => 64.50,
                'tax'         => 21,
                'stock'       => 20,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=spiritbox',
                'description' => 'Caja de espíritus con barrido de frecuencias AM/FM. Permite la comunicación en tiempo real con entidades.',
            ],
            [
                'sku'         => 'PHASMO-001',
                'title'       => 'Libro de Escritura Fantasmal',
                'provider'    => 'PhasmoGoods',
                'price'       => 15.00,
                'tax'         => 21,
                'stock'       => 50,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=book',
                'description' => 'Un libro en blanco diseñado para que espíritus anoten mensajes desde el más allá.',
            ],
            [
                'sku'         => 'PHASMO-002',
                'title'       => 'Proyector D.O.T.S.',
                'provider'    => 'PhasmoGoods',
                'price'       => 120.00,
                'tax'         => 21,
                'stock'       => 12,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=dots',
                'description' => 'Emite una matriz de lásers verdes que permite detectar la silueta de entes.',
            ],
            [
                'sku'         => 'PHASMO-003',
                'title'       => 'Crucifijo Consagrado',
                'provider'    => 'Iglesia Menor',
                'price'       => 35.00,
                'tax'         => 21,
                'stock'       => 100,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=cross',
                'description' => 'Previene que un espíritu materialice su cacería en un radio de 3 metros.',
            ],
            [
                'sku'         => 'PHASMO-004',
                'title'       => 'Inciensos Purificadores',
                'provider'    => 'PhasmoGoods',
                'price'       => 10.50,
                'tax'         => 21,
                'stock'       => 80,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=smudge',
                'description' => 'Al encenderlo frente a un fantasma, ciega temporalmente a la entidad.',
            ],
            [
                'sku'         => 'PHASMO-005',
                'title'       => 'Linterna UV',
                'provider'    => 'PhasmoGoods',
                'price'       => 22.00,
                'tax'         => 21,
                'stock'       => 40,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=uv',
                'description' => 'Luz ultravioleta enfocada para encontrar huellas ectoplásmicas dejadas en el entorno.',
            ],
            [
                'sku'         => 'PHASMO-006',
                'title'       => 'Píldoras de Cordura',
                'provider'    => 'PharmaGhost',
                'price'       => 45.00,
                'tax'         => 21,
                'stock'       => 60,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=pills',
                'description' => 'Restaura vitalidad mental tras eventos paralizantes graves.',
            ],
            [
                'sku'         => 'PHASMO-007',
                'title'       => 'Termómetro de Mercurio',
                'provider'    => 'RetroTools',
                'price'       => 18.50,
                'tax'         => 21,
                'stock'       => 30,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=thermo',
                'description' => 'Mide de forma exacta pero lenta la temperatura de la habitación para detectar temperaturas heladas.',
            ],
            [
                'sku'         => 'PHASMO-008',
                'title'       => 'Termómetro Láser (Tier II)',
                'provider'    => 'GhostTech Industries',
                'price'       => 85.00,
                'tax'         => 21,
                'stock'       => 22,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=thermot2',
                'description' => 'Lectura instantánea de temperatura con puntero láser.',
            ],
            [
                'sku'         => 'PHASMO-009',
                'title'       => 'Barra Luminosa (Glowstick)',
                'provider'    => 'LumenCo',
                'price'       => 4.99,
                'tax'         => 21,
                'stock'       => 150,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=glowstick',
                'description' => 'Fuente pasiva de luz ultravioleta. Especial para iluminar zonas de pasos.',
            ],
            [
                'sku'         => 'PHASMO-010',
                'title'       => 'Cámara de Fotos (Tier 1)',
                'provider'    => 'RetroTools',
                'price'       => 28.00,
                'tax'         => 21,
                'stock'       => 15,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=photocam1',
                'description' => 'Cámara de rollo desechable. Ideal para capturar fantasmas antes de huir.',
            ],
            [
                'sku'         => 'PHASMO-011',
                'title'       => 'Sensor de Movimiento',
                'provider'    => 'GhostTech Industries',
                'price'       => 42.00,
                'tax'         => 21,
                'stock'       => 24,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=motion',
                'description' => 'Emite una luz roja o verde según sea cruzado por vivos o fantasmas.',
            ],
            [
                'sku'         => 'PHASMO-012',
                'title'       => 'Sensor de Sonido',
                'provider'    => 'GhostTech Industries',
                'price'       => 50.00,
                'tax'         => 21,
                'stock'       => 14,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=sound',
                'description' => 'Micrófono de zona de amplio espectro. Conecta con el panel del camión.',
            ],
            [
                'sku'         => 'PHASMO-013',
                'title'       => 'Micrófono Parabólico',
                'provider'    => 'GhostTech Industries',
                'price'       => 110.00,
                'tax'         => 21,
                'stock'       => 9,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=paramic',
                'description' => 'Capta susurros paranormales a gran distancia a través de paredes.',
            ],
            [
                'sku'         => 'PHASMO-014',
                'title'       => 'Medidor EMF (Tier I)',
                'provider'    => 'RetroTools',
                'price'       => 15.00,
                'tax'         => 21,
                'stock'       => 10,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=emft1',
                'description' => 'Medidor electromagnético analógico con aguja. Poco fiable pero atmosférico.',
            ],
            [
                'sku'         => 'PHASMO-015',
                'title'       => 'Velas Consagradas',
                'provider'    => 'Iglesia Menor',
                'price'       => 6.50,
                'tax'         => 21,
                'stock'       => 200,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=candle',
                'description' => 'Mitigan un poco la pérdida de cordura en la oscuridad.',
            ],
            [
                'sku'         => 'PHASMO-016',
                'title'       => 'Mechero Zippo',
                'provider'    => 'FlameInc',
                'price'       => 12.00,
                'tax'         => 21,
                'stock'       => 45,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=lighter',
                'description' => 'Encendedor a prueba de viento esencial para prender inciensos y velas.',
            ],
            [
                'sku'         => 'PHASMO-017',
                'title'       => 'Trípode para Cámara',
                'provider'    => 'PhotoPro',
                'price'       => 65.00,
                'tax'         => 21,
                'stock'       => 18,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=tripod',
                'description' => 'Base estable para mantener la videocámara fijada apuntando a áreas clave.',
            ],
            [
                'sku'         => 'PHASMO-018',
                'title'       => 'Videocámara (Tier 1)',
                'provider'    => 'RetroTools',
                'price'       => 115.00,
                'tax'         => 21,
                'stock'       => 20,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=videocam1',
                'description' => 'Cámara de vídeo gruesa con visión nocturna muy difuminada.',
            ],
            [
                'sku'         => 'PHASMO-019',
                'title'       => 'Linterna Fuerte (Tier II)',
                'provider'    => 'LumenCo',
                'price'       => 25.00,
                'tax'         => 21,
                'stock'       => 35,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=flashlight2',
                'description' => 'Linterna clásica de buen rango de visión para explorar en semioscuridad.',
            ],
            [
                'sku'         => 'CURSED-001',
                'title'       => 'Cartas del Tarot',
                'provider'    => 'Objeto Maldito',
                'price'       => 666.00,
                'tax'         => 21,
                'stock'       => 3,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=tarot',
                'description' => 'Cada carta atrae fortuna o desesperación extrema. Juegas con tu vida.',
            ],
            [
                'sku'         => 'CURSED-002',
                'title'       => 'Tablero Ouija',
                'provider'    => 'Objeto Maldito',
                'price'       => 500.00,
                'tax'         => 21,
                'stock'       => 5,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=ouija',
                'description' => 'Formulad preguntas. El riesgo de cacería aumenta con el desgaste mental.',
            ],
            [
                'sku'         => 'CURSED-003',
                'title'       => 'Espejo Poseído',
                'provider'    => 'Objeto Maldito',
                'price'       => 450.00,
                'tax'         => 21,
                'stock'       => 4,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=mirror',
                'description' => 'Mirar la sala del fantasma a cambio de drenar tu cordura rápidamente.',
            ],
            [
                'sku'         => 'CURSED-004',
                'title'       => 'Caja de Música',
                'provider'    => 'Objeto Maldito',
                'price'       => 333.33,
                'tax'         => 21,
                'stock'       => 6,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=musicbox',
                'description' => 'Toca una dulce melodía. El fantasma cantará contigo, si te acercas demasiado...',
            ],
            [
                'sku'         => 'CURSED-005',
                'title'       => 'Muñeco Vudú',
                'provider'    => 'Objeto Maldito',
                'price'       => 280.00,
                'tax'         => 21,
                'stock'       => 8,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=voodoo',
                'description' => 'Fuerza interacciones del fantasma empujando alfileres en su suave tela.',
            ],
            [
                'sku'         => 'CURSED-006',
                'title'       => 'Pata de Mono',
                'provider'    => 'Objeto Maldito',
                'price'       => 777.00,
                'tax'         => 21,
                'stock'       => 2,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=monkeypaw',
                'description' => 'Concede todo lo que pidas, pero siempre hay un trágico precio a pagar.',
            ],
            [
                'sku'         => 'CURSED-007',
                'title'       => 'Círculo de Invocación',
                'provider'    => 'Objeto Maldito',
                'price'       => 999.99,
                'tax'         => 21,
                'stock'       => 1,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=circle',
                'description' => 'Enciende las velas. Materializa al espectro de inmediato para fotografiarlo.',
            ],
            [
                'sku'         => 'PHASMO-020',
                'title'       => 'Linterna de Cabeza (Tier 1)',
                'provider'    => 'GhostTech Industries',
                'price'       => 75.00,
                'tax'         => 21,
                'stock'       => 12,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=headlight1',
                'description' => 'Mantiene las manos libres en la profunda penumbra.',
            ],
            [
                'sku'         => 'PHASMO-021',
                'title'       => 'Cámara de Fotos (Tier II)',
                'provider'    => 'PhotoPro',
                'price'       => 85.00,
                'tax'         => 21,
                'stock'       => 15,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=photocam2',
                'description' => 'Digital con visor en pantalla. Mayor fiabilidad capturando siluetas rápidas.',
            ],
            [
                'sku'         => 'PHASMO-022',
                'title'       => 'Videocámara (Tier II)',
                'provider'    => 'GhostTech Industries',
                'price'       => 220.00,
                'tax'         => 21,
                'stock'       => 10,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=videocam2',
                'description' => 'Videocámara HD GhostHunting con visión nocturna estabilizada e interferencia reducida.',
            ],
            [
                'sku'         => 'PHASMO-023',
                'title'       => 'Libro de Escritura (Tier II)',
                'provider'    => 'PhasmoGoods',
                'price'       => 40.00,
                'tax'         => 21,
                'stock'       => 25,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=book2',
                'description' => 'Empaste grueso y bolígrafo consagrado para incitar mejor la escritura espectral.',
            ],
            [
                'sku'         => 'PHASMO-024',
                'title'       => 'Linterna Pro (Tier III)',
                'provider'    => 'LumenCo',
                'price'       => 55.00,
                'tax'         => 21,
                'stock'       => 18,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=flashlight3',
                'description' => 'Foco cegador con amplio rango lumínico que desgarra la mismísima oscuridad.',
            ],
            [
                'sku'         => 'PHASMO-025',
                'title'       => 'Ignitor Eléctrico',
                'provider'    => 'GhostTech Industries',
                'price'       => 25.00,
                'tax'         => 21,
                'stock'       => 20,
                'image'       => 'https://api.dicebear.com/9.x/shapes/svg?seed=ignitor',
                'description' => 'Soplete de seguridad ideal para encender rápido varios inciensos consecutivos.',
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}