<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'sku'         => 'EQ-EMF-K2',
                'title'       => 'Detector EMF K2 Pro',
                'provider'    => 'GhostTech Industries',
                'price'       => 49.99,
                'tax'         => 21,
                'stock'       => 25,
                'category'    => 'EQUIPMENT',
                'image'       => 'images/products/emf_k2.jpg',
                'description' => 'Detector de campos electromagnéticos profesional con 5 niveles de sensibilidad LED. Imprescindible en toda investigación paranormal.',
            ],
            [
                'sku'         => 'EQ-EVP-DIG',
                'title'       => 'Grabadora EVP Digital 32GB',
                'provider'    => 'SpiritSound Labs',
                'price'       => 89.95,
                'tax'         => 21,
                'stock'       => 15,
                'category'    => 'EQUIPMENT',
                'image'       => 'images/products/evp_recorder.jpg',
                'description' => 'Grabadora de voz de alta sensibilidad. Captura voces electrónicas de fenómenos paranormales con 32GB internos.',
            ],
            [
                'sku'         => 'EQ-CAM-THERM',
                'title'       => 'Cámara Térmica Nocturna',
                'provider'    => 'NightVision Corp',
                'price'       => 349.00,
                'tax'         => 21,
                'stock'       => 8,
                'category'    => 'EQUIPMENT',
                'image'       => 'images/products/thermal_cam.jpg',
                'description' => 'Cámara de visión nocturna con sensor térmico de alta resolución. Detecta variaciones de temperatura de hasta 0.05°C.',
            ],
            [
                'sku'         => 'EQ-SB-PSB7',
                'title'       => 'SpiritBox PSB-7',
                'provider'    => 'GhostTech Industries',
                'price'       => 64.50,
                'tax'         => 21,
                'stock'       => 20,
                'category'    => 'EQUIPMENT',
                'image'       => 'images/products/spiritbox.jpg',
                'description' => 'Caja de espíritus con barrido de frecuencias AM/FM. Permite la comunicación en tiempo real con entidades.',
            ],
            [
                'sku'         => 'EQ-SALT-VAT',
                'title'       => 'Sal Bendita Consagrada',
                'provider'    => 'Vatican Supplies',
                'price'       => 15.00,
                'tax'         => 21,
                'stock'       => 50,
                'category'    => 'PROTECTION',
                'image'       => 'images/products/salt.jpg',
                'description' => 'Sal marina pura ritualizada para protección perimetral contra entidades agresivas.',
            ],
            [
                'sku'         => 'EQ-DOTS-PRO',
                'title'       => 'Proyector D.O.T.S.',
                'provider'    => 'GhostTech Industries',
                'price'       => 120.00,
                'tax'         => 21,
                'stock'       => 12,
                'category'    => 'EQUIPMENT',
                'image'       => 'images/products/dots.jpg',
                'description' => 'Emite una matriz de lásers verdes que permite detectar la silueta de entes invisibles.',
            ],
            [
                'sku'         => 'EQ-CROSS-SILV',
                'title'       => 'Crucifijo de Plata',
                'provider'    => 'Reliquias de la Fe',
                'price'       => 35.00,
                'tax'         => 21,
                'stock'       => 100,
                'category'    => 'PROTECTION',
                'image'       => 'images/products/cross.jpg',
                'description' => 'Previene que un espíritu materialice su cacería en un radio de 3 metros.',
            ],
            [
                'sku'         => 'EQ-INC-PUR',
                'title'       => 'Inciensos Purificadores',
                'provider'    => 'Arcane Goods',
                'price'       => 10.50,
                'tax'         => 21,
                'stock'       => 80,
                'category'    => 'CONSUMABLE',
                'image'       => 'images/products/smudge.jpg',
                'description' => 'Al encenderlo frente a un fantasma, ciega temporalmente a la entidad y detiene el ataque.',
            ],
            [
                'sku'         => 'EQ-UV-LIGHT',
                'title'       => 'Linterna UV de Alta Potencia',
                'provider'    => 'Specter Tech',
                'price'       => 22.00,
                'tax'         => 21,
                'stock'       => 40,
                'category'    => 'EQUIPMENT',
                'image'       => 'images/products/uv_light.jpg',
                'description' => 'Luz ultravioleta enfocada para encontrar huellas ectoplásmicas y rastros invisibles.',
            ],
            [
                'sku'         => 'EQ-PILL-SANITY',
                'title'       => 'Píldoras de Cordura',
                'provider'    => 'PharmaGhost',
                'price'       => 45.00,
                'tax'         => 21,
                'stock'       => 60,
                'category'    => 'CONSUMABLE',
                'image'       => 'images/products/pills.jpg',
                'description' => 'Restaura vitalidad mental tras eventos paralizantes graves durante la investigación.',
            ],
            [
                'sku'         => 'EQ-FLASH-PRO',
                'title'       => 'Linterna Profesional Tier III',
                'provider'    => 'LumenCo',
                'price'       => 120.00,
                'tax'         => 21,
                'stock'       => 15,
                'category'    => 'EQUIPMENT',
                'image'       => 'images/products/flashlight_p3.jpg',
                'description' => 'La linterna más potente del mercado, capaz de iluminar grandes estancias al instante.',
            ],
            [
                'sku'         => 'EQ-MOTION-IR',
                'title'       => 'Sensor de Movimiento Infrarrojo',
                'provider'    => 'Specter Tech',
                'price'       => 75.00,
                'tax'         => 21,
                'stock'       => 30,
                'category'    => 'EQUIPMENT',
                'image'       => 'images/products/motion_ir.jpg',
                'description' => 'Detecta cambios en la radiación infrarroja emitida por objetos en movimiento.',
            ],
            [
                'sku'         => 'EQ-SOUND-AMP',
                'title'       => 'Amplificador de Sonido Parabólico',
                'provider'    => 'SpiritSound Labs',
                'price'       => 180.00,
                'tax'         => 21,
                'stock'       => 10,
                'category'    => 'EQUIPMENT',
                'image'       => 'images/products/sound_amp.jpg',
                'description' => 'Captura sonidos a grandes distancias y los amplifica para su análisis en tiempo real.',
            ],
            [
                'sku'         => 'EQ-TRIPOD-ST',
                'title'       => 'Trípode Estabilizador Pro',
                'provider'    => 'PhotoPro',
                'price'       => 55.00,
                'tax'         => 21,
                'stock'       => 20,
                'category'    => 'EQUIPMENT',
                'image'       => 'images/products/tripod.jpg',
                'description' => 'Base sólida para cámaras de video y sensores de precisión.',
            ],
            [
                'sku'         => 'EQ-GLOW-UV',
                'title'       => 'Barras Luminosas UV (Pack 10)',
                'provider'    => 'LumenCo',
                'price'       => 25.00,
                'tax'         => 21,
                'stock'       => 100,
                'category'    => 'CONSUMABLE',
                'image'       => 'images/products/glowsticks.jpg',
                'description' => 'Fuente de luz UV pasiva ideal para marcar rutas de escape en la oscuridad.',
            ],
            [
                'sku'         => 'EQ-BOOK-WR',
                'title'       => 'Libro de Escritura Automática',
                'provider'    => 'Arcane Goods',
                'price'       => 35.00,
                'tax'         => 21,
                'stock'       => 40,
                'category'    => 'EQUIPMENT',
                'image'       => 'images/products/ghost_book.jpg',
                'description' => 'Hojas tratadas para facilitar la interacción de entidades mediante escritura.',
            ],
            [
                'sku'         => 'EQ-TERM-LASER',
                'title'       => 'Termómetro Láser de Precisión',
                'provider'    => 'GhostTech Industries',
                'price'       => 65.00,
                'tax'         => 21,
                'stock'       => 25,
                'category'    => 'EQUIPMENT',
                'image'       => 'images/products/thermometer.jpg',
                'description' => 'Mide la temperatura de superficies de forma instantánea mediante puntero láser.',
            ],
            [
                'sku'         => 'EQ-PARAB-MIC',
                'title'       => 'Micrófono Parabólico Tier II',
                'provider'    => 'SpiritSound Labs',
                'price'       => 210.00,
                'tax'         => 21,
                'stock'       => 5,
                'category'    => 'EQUIPMENT',
                'image'       => 'images/products/parabolic_mic.jpg',
                'description' => 'Versión avanzada con filtrado de ruido digital integrado.',
            ],
            [
                'sku'         => 'EQ-HEAD-LIGHT',
                'title'       => 'Linterna Frontal de Minero',
                'provider'    => 'LumenCo',
                'price'       => 40.00,
                'tax'         => 21,
                'stock'       => 35,
                'category'    => 'EQUIPMENT',
                'image'       => 'images/products/headlight.jpg',
                'description' => 'Mantiene las manos libres durante la investigación con un potente haz de luz.',
            ],
            [
                'sku'         => 'EQ-GHOST-NET',
                'title'       => 'Red de Captura Ectoplásmica',
                'provider'    => 'Specter Tech',
                'price'       => 150.00,
                'tax'         => 21,
                'stock'       => 12,
                'category'    => 'EQUIPMENT',
                'image'       => 'images/products/ghost_net.jpg',
                'description' => 'Malla ionizada diseñada para retener partículas espectrales de forma temporal.',
            ],
            [
                'sku'         => 'EQ-HOLY-WATER',
                'title'       => 'Agua Bendita de Montserrat',
                'provider'    => 'Vatican Supplies',
                'price'       => 18.00,
                'tax'         => 21,
                'stock'       => 200,
                'category'    => 'CONSUMABLE',
                'image'       => 'images/products/holy_water.jpg',
                'description' => 'Ampolla de 100ml de agua bendecida en el santuario de Montserrat.',
            ],
            [
                'sku'         => 'EQ-SAGE-BUNDLE',
                'title'       => 'Atado de Salvia Blanca',
                'provider'    => 'Arcane Goods',
                'price'       => 12.00,
                'tax'         => 21,
                'stock'       => 150,
                'category'    => 'CONSUMABLE',
                'image'       => 'images/products/sage.jpg',
                'description' => 'Ideal para limpiezas energéticas rápidas en espacios reducidos.',
            ],
            [
                'sku'         => 'EQ-TAROT-CURSED',
                'title'       => 'Baraja de Tarot Arcaica',
                'provider'    => 'Arcane Goods',
                'price'       => 85.00,
                'tax'         => 21,
                'stock'       => 3,
                'category'    => 'CURSED',
                'image'       => 'images/products/tarot.jpg',
                'description' => 'Réplica fiel de una baraja del siglo XVIII con alta carga energética.',
            ],
            [
                'sku'         => 'EQ-OUIJA-BOARD',
                'title'       => 'Tablero Ouija de Madera de Roble',
                'provider'    => 'Arcane Goods',
                'price'       => 110.00,
                'tax'         => 21,
                'stock'       => 10,
                'category'    => 'CURSED',
                'image'       => 'images/products/ouija.jpg',
                'description' => 'Tablero tallado a mano con puntero equilibrado de precisión.',
            ],
            [
                'sku'         => 'EQ-GHOST-WATCH',
                'title'       => 'Reloj de Pulsera Detector EMF',
                'provider'    => 'GhostTech Industries',
                'price'       => 95.00,
                'tax'         => 21,
                'stock'       => 22,
                'category'    => 'EQUIPMENT',
                'image'       => 'images/products/watch_emf.jpg',
                'description' => 'Dispositivo discreto que vibra al detectar anomalías electromagnéticas.',
            ],
            [
                'sku'         => 'EQ-LENS-UV',
                'title'       => 'Filtro de Lente UV para Cámara',
                'provider'    => 'PhotoPro',
                'price'       => 30.00,
                'tax'         => 21,
                'stock'       => 50,
                'category'    => 'EQUIPMENT',
                'image'       => 'images/products/uv_filter.jpg',
                'description' => 'Mejora la visibilidad de orbes y rastros bajo luz ultravioleta.',
            ],
            [
                'sku'         => 'EQ-SALT-GUN',
                'title'       => 'Lanzador de Sal de Aire Comprimido',
                'provider'    => 'Specter Tech',
                'price'       => 195.00,
                'tax'         => 21,
                'stock'       => 8,
                'category'    => 'EQUIPMENT',
                'image'       => 'images/products/salt_gun.jpg',
                'description' => 'Dispersa sal ritualizada en un amplio radio de forma rápida y segura.',
            ],
            [
                'sku'         => 'EQ-ECTO-TRAP',
                'title'       => 'Trampa de Vacío de Ectoplasma',
                'provider'    => 'GhostTech Industries',
                'price'       => 250.00,
                'tax'         => 21,
                'stock'       => 4,
                'category'    => 'EQUIPMENT',
                'image'       => 'images/products/ecto_trap.jpg',
                'description' => 'Contenedor hermético para muestras físicas de residuos fantasmales.',
            ],
            [
                'sku'         => 'EQ-GHOST-BOX-BT',
                'title'       => 'Spirit Box con Bluetooth',
                'provider'    => 'SpiritSound Labs',
                'price'       => 140.00,
                'tax'         => 21,
                'stock'       => 18,
                'category'    => 'EQUIPMENT',
                'image'       => 'images/products/ghost_box_bt.jpg',
                'description' => 'Sincroniza tus grabaciones directamente con tu dispositivo móvil.',
            ],
            [
                'sku'         => 'EQ-PROTECT-VEST',
                'title'       => 'Chaleco de Protección de Kevlar',
                'provider'    => 'SafetyFirst',
                'price'       => 320.00,
                'tax'         => 21,
                'stock'       => 6,
                'category'    => 'PROTECTION',
                'image'       => 'images/products/vest.jpg',
                'description' => 'Protección física contra ataques de poltergeist y objetos lanzados.',
            ],
            [
                'sku'         => 'EQ-CANDLE-RIT',
                'title'       => 'Pack de 10 Velas Negras',
                'provider'    => 'Arcane Goods',
                'price'       => 15.00,
                'tax'         => 21,
                'stock'       => 100,
                'category'    => 'CONSUMABLE',
                'image'       => 'images/products/candles.jpg',
                'description' => 'Velas de cera de abeja pura para rituales de invocación y protección.',
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}